<a href="https://colab.research.google.com/github/pratyushagnihotri03/Python_Programming/blob/master/Python_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from numpy import *

arr = array([1,2,3,4,5])
carr = array(['a','b','c'])
sarr = array(['python','java','rest'])

print(arr)
print(carr)
print(sarr)

In [ ]:
print(linspace(0,100,50))

In [ ]:
print(logspace(1,20))

In [ ]:
print(arange(1,5))
print(arange(5,1,-1))

In [ ]:
print(zeros(10))
print(ones(10))

In [ ]:
# mathmatical functions

a1 = array([1,2,3,4])
a2 = array([10,11,12,13])

print(a1+a2)
print(a1-2)
print(sin(a1))
print(mean(a1))
print(abs(a1))
print(min(a1))
print(sum(a2))

In [ ]:
# array comparison

a1 = ([10,30,50,70,100])
a2 = ([20,40,60,80,100])

print(a1 >= a2)
print(a1 < a2)

print(all(a1 <= a2))
print(any(a1 <= a2))

print(logical_or(a1<10, a1<101))

print(where(a1%2!=0,a1,0))
print(where(a1<a2,a1,a2))

In [ ]:
# Copying the array

a1 = arange(1,10)
a2 = a1.view()

print('a1',a1)
print('a2',a2)

a2[3]=40
print('after modification')
print('a1',a1)
print('a2',a2)

In [ ]:
a1 = arange(1,10)
a2 = a1.copy()

print('a1',a1)
print('a2',a2)

a2[3]=40
print('after modification')
print('a1',a1)
print('a2',a2)

In [ ]:
# slicing

a1 = arange(1,20)

print('a1',a1)
print(a1[3:7])
print(a1[1:9:2])
print(a1[4])

In [ ]:
# Multidimensional array

a1 = array([1,2,3,4,5,6])
a2 = array([[1,2,3],[4,5,6]])
a3 = array([[[1,2,3],[3,4,5]],[[7,8,9],[1,2,3]]])

print(a1)
print(a2)
print(a3)

print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

print(a1.shape)
print(a2.shape)
print(a3.shape)

print(a1.size)
print(a2.size)
print(a3.size)

print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

print(a1.nbytes)
print(a2.nbytes)
print(a3.nbytes)


In [30]:
a1 = arange(12)
print('a1',a1)

a2 = reshape(a1,(4,3))
print('a2',a2)

a3 = reshape(a1,(2,2,3))
print('a3',a3)

print('a3',a3.flatten())

print(eye(3))

a1 [ 0  1  2  3  4  5  6  7  8  9 10 11]
a2 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
a3 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
a3 [ 0  1  2  3  4  5  6  7  8  9 10 11]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
